/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UUID = IDL.Nat;
export const Time = IDL.Int;
export const Appointment = IDL.Record({
  'clientId' : UUID,
  'date' : Time,
  'description' : IDL.Text,
  'confirmed' : IDL.Bool,
  'vehicleId' : UUID,
});
export const Part = IDL.Record({
  'partNumber' : IDL.Text,
  'name' : IDL.Text,
  'minStock' : IDL.Nat,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'unitCost' : IDL.Nat,
});
export const Vehicle = IDL.Record({
  'vin' : IDL.Text,
  'model' : IDL.Text,
  'clientId' : UUID,
  'licensePlate' : IDL.Text,
  'year' : IDL.Nat,
  'notes' : IDL.Text,
  'brand' : IDL.Text,
});
export const WorkOrderStatus = IDL.Variant({
  'awaitingParts' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const WorkOrder = IDL.Record({
  'status' : WorkOrderStatus,
  'clientId' : UUID,
  'createdAt' : Time,
  'dueDate' : IDL.Opt(Time),
  'totalCost' : IDL.Nat,
  'description' : IDL.Text,
  'notes' : IDL.Text,
  'assignedTech' : IDL.Text,
  'vehicleId' : UUID,
});
export const Client = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppointment' : IDL.Func([Appointment], [UUID], []),
  'createClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [UUID], []),
  'createPart' : IDL.Func([Part], [UUID], []),
  'createVehicle' : IDL.Func([Vehicle], [UUID], []),
  'createWorkOrder' : IDL.Func([WorkOrder], [UUID], []),
  'deleteAppointment' : IDL.Func([UUID], [], []),
  'deleteClient' : IDL.Func([UUID], [], []),
  'deletePart' : IDL.Func([UUID], [], []),
  'deleteVehicle' : IDL.Func([UUID], [], []),
  'deleteWorkOrder' : IDL.Func([UUID], [], []),
  'getActiveJobsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllParts' : IDL.Func([], [IDL.Vec(Part)], ['query']),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getAllWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
  'getAppointment' : IDL.Func([UUID], [Appointment], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([UUID], [Client], ['query']),
  'getPart' : IDL.Func([UUID], [Part], ['query']),
  'getPartsBelowMinStock' : IDL.Func([], [IDL.Vec(Part)], ['query']),
  'getTodayAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVehicle' : IDL.Func([UUID], [Vehicle], ['query']),
  'getVehiclesInShop' : IDL.Func([], [IDL.Nat], ['query']),
  'getWorkOrder' : IDL.Func([UUID], [WorkOrder], ['query']),
  'getWorkOrdersByClient' : IDL.Func([UUID], [IDL.Vec(WorkOrder)], ['query']),
  'getWorkOrdersByStatus' : IDL.Func(
      [WorkOrderStatus],
      [IDL.Vec(WorkOrder)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppointment' : IDL.Func([UUID, Appointment], [], []),
  'updateClient' : IDL.Func([UUID, Client], [], []),
  'updatePart' : IDL.Func([UUID, Part], [], []),
  'updateVehicle' : IDL.Func([UUID, Vehicle], [], []),
  'updateWorkOrder' : IDL.Func([UUID, WorkOrder], [], []),
  'updateWorkOrderStatus' : IDL.Func([UUID, WorkOrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UUID = IDL.Nat;
  const Time = IDL.Int;
  const Appointment = IDL.Record({
    'clientId' : UUID,
    'date' : Time,
    'description' : IDL.Text,
    'confirmed' : IDL.Bool,
    'vehicleId' : UUID,
  });
  const Part = IDL.Record({
    'partNumber' : IDL.Text,
    'name' : IDL.Text,
    'minStock' : IDL.Nat,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'unitCost' : IDL.Nat,
  });
  const Vehicle = IDL.Record({
    'vin' : IDL.Text,
    'model' : IDL.Text,
    'clientId' : UUID,
    'licensePlate' : IDL.Text,
    'year' : IDL.Nat,
    'notes' : IDL.Text,
    'brand' : IDL.Text,
  });
  const WorkOrderStatus = IDL.Variant({
    'awaitingParts' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const WorkOrder = IDL.Record({
    'status' : WorkOrderStatus,
    'clientId' : UUID,
    'createdAt' : Time,
    'dueDate' : IDL.Opt(Time),
    'totalCost' : IDL.Nat,
    'description' : IDL.Text,
    'notes' : IDL.Text,
    'assignedTech' : IDL.Text,
    'vehicleId' : UUID,
  });
  const Client = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppointment' : IDL.Func([Appointment], [UUID], []),
    'createClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [UUID], []),
    'createPart' : IDL.Func([Part], [UUID], []),
    'createVehicle' : IDL.Func([Vehicle], [UUID], []),
    'createWorkOrder' : IDL.Func([WorkOrder], [UUID], []),
    'deleteAppointment' : IDL.Func([UUID], [], []),
    'deleteClient' : IDL.Func([UUID], [], []),
    'deletePart' : IDL.Func([UUID], [], []),
    'deleteVehicle' : IDL.Func([UUID], [], []),
    'deleteWorkOrder' : IDL.Func([UUID], [], []),
    'getActiveJobsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllParts' : IDL.Func([], [IDL.Vec(Part)], ['query']),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getAllWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
    'getAppointment' : IDL.Func([UUID], [Appointment], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([UUID], [Client], ['query']),
    'getPart' : IDL.Func([UUID], [Part], ['query']),
    'getPartsBelowMinStock' : IDL.Func([], [IDL.Vec(Part)], ['query']),
    'getTodayAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVehicle' : IDL.Func([UUID], [Vehicle], ['query']),
    'getVehiclesInShop' : IDL.Func([], [IDL.Nat], ['query']),
    'getWorkOrder' : IDL.Func([UUID], [WorkOrder], ['query']),
    'getWorkOrdersByClient' : IDL.Func([UUID], [IDL.Vec(WorkOrder)], ['query']),
    'getWorkOrdersByStatus' : IDL.Func(
        [WorkOrderStatus],
        [IDL.Vec(WorkOrder)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppointment' : IDL.Func([UUID, Appointment], [], []),
    'updateClient' : IDL.Func([UUID, Client], [], []),
    'updatePart' : IDL.Func([UUID, Part], [], []),
    'updateVehicle' : IDL.Func([UUID, Vehicle], [], []),
    'updateWorkOrder' : IDL.Func([UUID, WorkOrder], [], []),
    'updateWorkOrderStatus' : IDL.Func([UUID, WorkOrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };