/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'clientId' : UUID,
  'date' : Time,
  'description' : string,
  'confirmed' : boolean,
  'vehicleId' : UUID,
}
export interface Client {
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'phone' : string,
}
export interface Part {
  'partNumber' : string,
  'name' : string,
  'minStock' : bigint,
  'quantity' : bigint,
  'category' : string,
  'unitCost' : bigint,
}
export type Time = bigint;
export type UUID = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'vin' : string,
  'model' : string,
  'clientId' : UUID,
  'licensePlate' : string,
  'year' : bigint,
  'notes' : string,
  'brand' : string,
}
export interface WorkOrder {
  'status' : WorkOrderStatus,
  'clientId' : UUID,
  'createdAt' : Time,
  'dueDate' : [] | [Time],
  'totalCost' : bigint,
  'description' : string,
  'notes' : string,
  'assignedTech' : string,
  'vehicleId' : UUID,
}
export type WorkOrderStatus = { 'awaitingParts' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppointment' : ActorMethod<[Appointment], UUID>,
  'createClient' : ActorMethod<[string, string, string], UUID>,
  'createPart' : ActorMethod<[Part], UUID>,
  'createVehicle' : ActorMethod<[Vehicle], UUID>,
  'createWorkOrder' : ActorMethod<[WorkOrder], UUID>,
  'deleteAppointment' : ActorMethod<[UUID], undefined>,
  'deleteClient' : ActorMethod<[UUID], undefined>,
  'deletePart' : ActorMethod<[UUID], undefined>,
  'deleteVehicle' : ActorMethod<[UUID], undefined>,
  'deleteWorkOrder' : ActorMethod<[UUID], undefined>,
  'getActiveJobsCount' : ActorMethod<[], bigint>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllParts' : ActorMethod<[], Array<Part>>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getAllWorkOrders' : ActorMethod<[], Array<WorkOrder>>,
  'getAppointment' : ActorMethod<[UUID], Appointment>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[UUID], Client>,
  'getPart' : ActorMethod<[UUID], Part>,
  'getPartsBelowMinStock' : ActorMethod<[], Array<Part>>,
  'getTodayAppointments' : ActorMethod<[], Array<Appointment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVehicle' : ActorMethod<[UUID], Vehicle>,
  'getVehiclesInShop' : ActorMethod<[], bigint>,
  'getWorkOrder' : ActorMethod<[UUID], WorkOrder>,
  'getWorkOrdersByClient' : ActorMethod<[UUID], Array<WorkOrder>>,
  'getWorkOrdersByStatus' : ActorMethod<[WorkOrderStatus], Array<WorkOrder>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppointment' : ActorMethod<[UUID, Appointment], undefined>,
  'updateClient' : ActorMethod<[UUID, Client], undefined>,
  'updatePart' : ActorMethod<[UUID, Part], undefined>,
  'updateVehicle' : ActorMethod<[UUID, Vehicle], undefined>,
  'updateWorkOrder' : ActorMethod<[UUID, WorkOrder], undefined>,
  'updateWorkOrderStatus' : ActorMethod<[UUID, WorkOrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];