/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Part {
    partNumber: string;
    name: string;
    minStock: bigint;
    quantity: bigint;
    category: string;
    unitCost: bigint;
}
export type Time = bigint;
export interface WorkOrder {
    status: WorkOrderStatus;
    clientId: UUID;
    createdAt: Time;
    dueDate?: Time;
    totalCost: bigint;
    description: string;
    notes: string;
    assignedTech: string;
    vehicleId: UUID;
}
export type UUID = bigint;
export interface Client {
    name: string;
    createdAt: Time;
    email: string;
    phone: string;
}
export interface Appointment {
    clientId: UUID;
    date: Time;
    description: string;
    confirmed: boolean;
    vehicleId: UUID;
}
export interface Vehicle {
    vin: string;
    model: string;
    clientId: UUID;
    licensePlate: string;
    year: bigint;
    notes: string;
    brand: string;
}
export interface UserProfile {
    name: string;
    role: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WorkOrderStatus {
    awaitingParts = "awaitingParts",
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAppointment(appointment: Appointment): Promise<UUID>;
    createClient(name: string, phone: string, email: string): Promise<UUID>;
    createPart(part: Part): Promise<UUID>;
    createVehicle(vehicle: Vehicle): Promise<UUID>;
    createWorkOrder(workOrder: WorkOrder): Promise<UUID>;
    deleteAppointment(id: UUID): Promise<void>;
    deleteClient(id: UUID): Promise<void>;
    deletePart(id: UUID): Promise<void>;
    deleteVehicle(id: UUID): Promise<void>;
    deleteWorkOrder(id: UUID): Promise<void>;
    getActiveJobsCount(): Promise<bigint>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllClients(): Promise<Array<Client>>;
    getAllParts(): Promise<Array<Part>>;
    getAllVehicles(): Promise<Array<Vehicle>>;
    getAllWorkOrders(): Promise<Array<WorkOrder>>;
    getAppointment(id: UUID): Promise<Appointment>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(id: UUID): Promise<Client>;
    getPart(id: UUID): Promise<Part>;
    getPartsBelowMinStock(): Promise<Array<Part>>;
    getTodayAppointments(): Promise<Array<Appointment>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVehicle(id: UUID): Promise<Vehicle>;
    getVehiclesInShop(): Promise<bigint>;
    getWorkOrder(id: UUID): Promise<WorkOrder>;
    getWorkOrdersByClient(clientId: UUID): Promise<Array<WorkOrder>>;
    getWorkOrdersByStatus(status: WorkOrderStatus): Promise<Array<WorkOrder>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAppointment(id: UUID, appointment: Appointment): Promise<void>;
    updateClient(id: UUID, client: Client): Promise<void>;
    updatePart(id: UUID, part: Part): Promise<void>;
    updateVehicle(id: UUID, vehicle: Vehicle): Promise<void>;
    updateWorkOrder(id: UUID, workOrder: WorkOrder): Promise<void>;
    updateWorkOrderStatus(id: UUID, status: WorkOrderStatus): Promise<void>;
}
import type { Time as _Time, UUID as _UUID, UserProfile as _UserProfile, UserRole as _UserRole, WorkOrder as _WorkOrder, WorkOrderStatus as _WorkOrderStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAppointment(arg0: Appointment): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0);
            return result;
        }
    }
    async createClient(arg0: string, arg1: string, arg2: string): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0, arg1, arg2);
            return result;
        }
    }
    async createPart(arg0: Part): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createPart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPart(arg0);
            return result;
        }
    }
    async createVehicle(arg0: Vehicle): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVehicle(arg0);
            return result;
        }
    }
    async createWorkOrder(arg0: WorkOrder): Promise<UUID> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkOrder(to_candid_WorkOrder_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkOrder(to_candid_WorkOrder_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteAppointment(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteClient(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deletePart(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePart(arg0);
            return result;
        }
    }
    async deleteVehicle(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVehicle(arg0);
            return result;
        }
    }
    async deleteWorkOrder(arg0: UUID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkOrder(arg0);
            return result;
        }
    }
    async getActiveJobsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveJobsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveJobsCount();
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return result;
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllParts(): Promise<Array<Part>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParts();
            return result;
        }
    }
    async getAllVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVehicles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVehicles();
            return result;
        }
    }
    async getAllWorkOrders(): Promise<Array<WorkOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkOrders();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkOrders();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointment(arg0: UUID): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: UUID): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return result;
        }
    }
    async getPart(arg0: UUID): Promise<Part> {
        if (this.processError) {
            try {
                const result = await this.actor.getPart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPart(arg0);
            return result;
        }
    }
    async getPartsBelowMinStock(): Promise<Array<Part>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartsBelowMinStock();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartsBelowMinStock();
            return result;
        }
    }
    async getTodayAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayAppointments();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVehicle(arg0: UUID): Promise<Vehicle> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicle(arg0);
            return result;
        }
    }
    async getVehiclesInShop(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehiclesInShop();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehiclesInShop();
            return result;
        }
    }
    async getWorkOrder(arg0: UUID): Promise<WorkOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkOrder(arg0);
                return from_candid_WorkOrder_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkOrder(arg0);
            return from_candid_WorkOrder_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkOrdersByClient(arg0: UUID): Promise<Array<WorkOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkOrdersByClient(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkOrdersByClient(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkOrdersByStatus(arg0: WorkOrderStatus): Promise<Array<WorkOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkOrdersByStatus(to_candid_WorkOrderStatus_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkOrdersByStatus(to_candid_WorkOrderStatus_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAppointment(arg0: UUID, arg1: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(arg0, arg1);
            return result;
        }
    }
    async updateClient(arg0: UUID, arg1: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1);
            return result;
        }
    }
    async updatePart(arg0: UUID, arg1: Part): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePart(arg0, arg1);
            return result;
        }
    }
    async updateVehicle(arg0: UUID, arg1: Vehicle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVehicle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVehicle(arg0, arg1);
            return result;
        }
    }
    async updateWorkOrder(arg0: UUID, arg1: WorkOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkOrder(arg0, to_candid_WorkOrder_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkOrder(arg0, to_candid_WorkOrder_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateWorkOrderStatus(arg0: UUID, arg1: WorkOrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkOrderStatus(arg0, to_candid_WorkOrderStatus_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkOrderStatus(arg0, to_candid_WorkOrderStatus_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_WorkOrderStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkOrderStatus): WorkOrderStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_WorkOrder_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkOrder): WorkOrder {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _WorkOrderStatus;
    clientId: _UUID;
    createdAt: _Time;
    dueDate: [] | [_Time];
    totalCost: bigint;
    description: string;
    notes: string;
    assignedTech: string;
    vehicleId: _UUID;
}): {
    status: WorkOrderStatus;
    clientId: UUID;
    createdAt: Time;
    dueDate?: Time;
    totalCost: bigint;
    description: string;
    notes: string;
    assignedTech: string;
    vehicleId: UUID;
} {
    return {
        status: from_candid_WorkOrderStatus_n10(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.dueDate)),
        totalCost: value.totalCost,
        description: value.description,
        notes: value.notes,
        assignedTech: value.assignedTech,
        vehicleId: value.vehicleId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    awaitingParts: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): WorkOrderStatus {
    return "awaitingParts" in value ? WorkOrderStatus.awaitingParts : "cancelled" in value ? WorkOrderStatus.cancelled : "pending" in value ? WorkOrderStatus.pending : "completed" in value ? WorkOrderStatus.completed : "inProgress" in value ? WorkOrderStatus.inProgress : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkOrder>): Array<WorkOrder> {
    return value.map((x)=>from_candid_WorkOrder_n8(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WorkOrderStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkOrderStatus): _WorkOrderStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_WorkOrder_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkOrder): _WorkOrder {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: WorkOrderStatus;
    clientId: UUID;
    createdAt: Time;
    dueDate?: Time;
    totalCost: bigint;
    description: string;
    notes: string;
    assignedTech: string;
    vehicleId: UUID;
}): {
    status: _WorkOrderStatus;
    clientId: _UUID;
    createdAt: _Time;
    dueDate: [] | [_Time];
    totalCost: bigint;
    description: string;
    notes: string;
    assignedTech: string;
    vehicleId: _UUID;
} {
    return {
        status: to_candid_WorkOrderStatus_n5(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        createdAt: value.createdAt,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        totalCost: value.totalCost,
        description: value.description,
        notes: value.notes,
        assignedTech: value.assignedTech,
        vehicleId: value.vehicleId
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkOrderStatus): {
    awaitingParts: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == WorkOrderStatus.awaitingParts ? {
        awaitingParts: null
    } : value == WorkOrderStatus.cancelled ? {
        cancelled: null
    } : value == WorkOrderStatus.pending ? {
        pending: null
    } : value == WorkOrderStatus.completed ? {
        completed: null
    } : value == WorkOrderStatus.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
